name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build
        run: ./scripts/buildprod.sh

      - name: migrateup.sh
        run: ./scripts/migrateup.sh
      # - id: "auth"
      #   uses: "google-github-actions/auth@v2"
      #   with:
      #     credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      # - name: "Set up Cloud SDK"
      #   uses: "google-github-actions/setup-gcloud@v2"

      # - name: "Use gcloud CLI"
      #   run: "gcloud info"

      # - name: "Push to Google Artifact Registery - submit to gcloud"
      #   run: gcloud builds submit --tag europe-west10-docker.pkg.dev/notely-434514/notely-ar-repo/gokdenizozkan/notely:latest
